version: '3'
services:

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-CU27-ubuntu-20.04
    container_name: mssql-db
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P ${DB_PASSWORD} -Q 'SELECT 1' || exit 1" ]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    build:
      context: backend
    depends_on:
      mssql-server:
        condition: service_healthy
    container_name: backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PORT=${BACKEND_PORT}
      - SQL_HOST=${SQL_HOST}
      - SQL_PORT=${SQL_PORT}
      - SQL_NAME=${SQL_NAME}
      - SQL_USER=${SQL_USER}
      - SQL_PASSWORD=${DB_PASSWORD}   #changing the env name from DB_PASSWORD to SQL_PASSWORD when passing to backend
      - CLIENT_ID=${CLIENT_ID}
      - ISSUER_BASE_URL=${ISSUER_BASE_URL}
      - AUTH0_SECRET=${AUTH0_SECRET}
      - BASE_URL=${BASE_URL}

  frontend:
    build:
      context: ./frontend
    depends_on:
      backend:
        condition: service_started
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      - PORT=${FRONTEND_PORT}
