import { Knex } from "knex";

export async function seed(knex: Knex): Promise<void> {
    // Deletes ALL existing entries
    await knex("tags").del();

    // Inserts seed entries
    await knex("tags").insert([
        { name: "Favourites" },
        { name: "Moms smut" },
        { name: "Classic" },
        { name: "Need to read" },
        { name: "Must read" },
        { name: "Later" },
        { name: "Science Fiction" },
        { name: "Fantasy" },
        { name: "Non-fiction" },
        { name: "Biography" },
        { name: "Historical" },
        { name: "Romance" },
        { name: "Thriller" },
        { name: "Mystery" },
        { name: "Horror" },
        { name: "Young Adult" },
        { name: "Children's" },
        { name: "Adventure" },
        { name: "Humor" },
        { name: "Self-help" },
        { name: "Health & Wellness" },
        { name: "Cookbooks" },
        { name: "Poetry" },
        { name: "Drama" },
        { name: "Short Stories" },
        { name: "Classics" },
        { name: "Philosophy" },
        { name: "Politics" },
        { name: "Economics" },
        { name: "Spirituality" },
        { name: "Religion" },
        { name: "Travel" },
        { name: "Memoir" },
        { name: "Autobiography" },
        { name: "Art" },
        { name: "Photography" },
        { name: "Music" },
        { name: "Sports" },
        { name: "Nature" },
        { name: "Science" },
        { name: "Technology" },
        { name: "Programming" },
        { name: "Business" },
        { name: "Marketing" },
        { name: "Entrepreneurship" },
        { name: "Psychology" },
        { name: "Education" },
        { name: "Parenting" },
        { name: "Animals" },
        { name: "Home & Garden" },
        { name: "DIY" },
        { name: "Crafts" },
        { name: "Comics" },
        { name: "Graphic Novels" },
        { name: "Manga" },
        { name: "Anime" },
        { name: "War" },
        { name: "Military" },
        { name: "Western" },
    ]);
}
