# Use the official Microsoft SQL Server image
FROM mcr.microsoft.com/mssql/server:2019-latest

ARG SA_PASSWORD

# Set environment variables
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=$SA_PASSWORD

# Copy the SQL script into the container
COPY create-db.sql /create-db.sql

# Copy custom entrypoint script
COPY entrypoint.sh /entrypoint.sh

# Set execute permissions for the entrypoint script
RUN chmod +x /entrypoint.sh

# Set the custom entrypoint script as the entrypoint
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
