# Use the official Microsoft SQL Server image
FROM mcr.microsoft.com/mssql/server:2019-CU14-ubuntu-20.04

ARG SA_PASSWORD

# Set environment variables
ENV ACCEPT_EULA=Y
ENV SA_PASSWORD=$SA_PASSWORD

# Copy SQL script and entrypoint script into the container
COPY create-db.sql /create-db.sql
COPY entrypoint.sh /entrypoint.sh

# Make entrypoint.sh executable as root and set entrypoint
RUN chmod +x /entrypoint.sh

# Set the custom entrypoint script as the entrypoint
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]