# 1. Use an official Node.js runtime as the base image
FROM node:20

ARG PORT
ARG SQL_HOST
ARG SQL_PORT
ARG SQL_NAME
ARG SQL_USER
ARG SQL_PASSWORD

ENV PORT=$PORT
ENV SQL_HOST=$SQL_HOST
ENV SQL_PORT=$SQL_PORT
ENV SQL_NAME=$SQL_NAME
ENV SQL_USER=$SQL_USER
ENV SQL_PASSWORD=$SQL_PASSWORD

# 2. Set the working directory
WORKDIR /usr/src/app

# 3. Copy the package.json and package-lock.json to install dependencies
COPY package*.json ./

# 4. Install dependencies
RUN npm install --production

# 5. Copy the rest of the application code to the container
COPY . .

# 6. Expose the port the app runs on
EXPOSE $PORT

# 7. Start the app
CMD ["npm", "start"]