name: Run tests and SonarQube Analysis

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2019-CU27-ubuntu-20.04
        env:
          SA_PASSWORD: ${{ secrets.DB_PASSWORD }}
          ACCEPT_EULA: Y
        ports:
          - 1433:1433

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install backend dependencies
        run: npm install
        working-directory: ./backend

      - name: Wait for MSSQL to be ready
        run: |
          for i in {1..15}; do
              if sqlcmd -S localhost -U sa -P ${{ secrets.DB_PASSWORD }} -Q "SELECT 1" -b; then
              echo "MSSQL is ready!"
              break
              fi
              echo "Waiting for MSSQL to be ready... attempt $i"
              sleep 5
          done

      - name: Install ts-node
        run: npm install -g ts-node

      - name: Run Backend tests and generate coverage
        run: npm test -- --coverage
        working-directory: ./backend
        env:
          SQL_USER: sa
          SQL_PASSWORD: ${{ secrets.DB_PASSWORD }}
          SQL_HOST: localhost
          TEST_SQL_NAME: bookCollectionTest
          ISBNDB_API_KEY: ${{ secrets.ISBNDB_API_KEY }}
          NODE_ENV: test
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD }}

      - name: Install Sonar Scanner
        run: |
          curl -sSLo sonar-scanner-cli.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner-cli.zip
          echo "$(pwd)/sonar-scanner-5.0.1.3006-linux/bin" >> $GITHUB_PATH

      - name: Run SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=No-Life-inc_semester_project \
            -Dsonar.organization=no-life-inc \
            -Dsonar.sources=./backend,./frontend/src \
            -Dsonar.exclusions=**/__tests__/**,**/__tests__/integrationTests/**,\
          **/controllers/mongo/**,**/controllers/neo4j/**,**/database/**/**,\
          **/dbconnections/MongoConnection.ts,**/dbconnections/Neo4jConnection.ts,\
          **/models/mongoose/**,**/models/neo4j/**,**/routes/mongo/**,**/routes/neo4j/**,\
          **/services/mongo/**,**/services/neo4j/**,**/config/**,frontend/**\
            -Dsonar.javascript.lcov.reportPaths=./backend/coverage/lcov.info \
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
